class Lilypond
  LILYPOND_VERSION='2.14.1'
  INDENT = ' '*2
  def self.output_extension; '.gly' end
  def self.rest; rest='r1*' end
  def self.write_input_for_lilypond movement, instrument, filepath
    lilypond_variable_name, mode, overall_prefix = Main.three_keys
    a=Array.new
    a.push %Q@\\version "#{LILYPOND_VERSION}"@
    a.push "% This file was autogenerated. DO NOT MODIFY.\n"
    a.push "#{lilypond_variable_name} = {"
    a.push "#{INDENT}\\#{mode} {"
    overall_prefix.each{|e| a.push "#{INDENT}#{INDENT}#{e}"} unless overall_prefix.nil?
    a.push instrument.hash.values_at(*movement.measure_keys).map{|e| e.to_s}.join "\n"
    a.push "#{INDENT}}"
    a.push "}"
    s=a.join "\n"
    f=File.new filepath, 'w'
    f.print s, "\n"
    f.close
  end
end
