class LilyPond #:nodoc: all
  INDENT = ' '*2
  LILYPOND_VERSION='2.14.1'
  OUTPUT_EXTENSION='.gly'
  def self.output_extension; OUTPUT_EXTENSION end
  def self.rest; rest='r1*' end
  def self.write_input_for_lilypond movement, instrument, filepath
    lilypond_variable_name, mode, overall_prefix = Main.three_keys
    a=Array.new
    a.push %Q@\\version "#{LILYPOND_VERSION}"@
    a.push "% This file was autogenerated. DO NOT MODIFY.\n"
    a.push "#{lilypond_variable_name} = {"
    a.push "#{INDENT}\\#{mode} {" # Keep a separate line, as may contain a LilyPond line comment.
    overall_prefix.each{|e| a.push "#{INDENT}#{INDENT}#{e}"} unless overall_prefix.nil?
    a.push instrument.hash.values_at(*movement.measure_keys).map{|e| e.to_s}.join "\n" # Value is Measure.
    a.push "#{INDENT}}"
    a.push "}"
    s=a.join "\n"
    f=File.new filepath, 'wb' # Use Unix (LF) line endings.
    f.print s, "\n"
    f.close
  end
end
